DEVICE          : cuda              # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'C:\final_project_eran_nadav\semantic-segmentation-main\output\elbit_results\test_results'         # output folder name used for saving the model, logs and inference results

MODEL:                                    
  NAME          : SegFormer                                           # name of the model you are using
  BACKBONE      : MiT-B3                                                  # model variant
  PRETRAINED    : 'C:\final_project_eran_nadav\semantic-segmentation-main/checkpoints/pretrained/segformer/mit_b3.pth'              # backbone model's weight+
  CHECKPOINT    : 'C:\final_project_eran_nadav\semantic-segmentation-main\checkpoints\model\elbit\'

DATASET:
  NAME          : Elbit                           # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : 'C:\final_project_eran_nadav\semantic-segmentation-main\data\elbit_dataset\shuffeled_dataset'                          # dataset root path
  IGNORE_LABEL  : 255

TRAIN:
  IMAGE_SIZE    : [540, 960]    # training image size in (h, w)
  BATCH_SIZE    : 4              # batch size used to train
  EPOCHS        : 500             # number of epochs to train
  EVAL_INTERVAL : 10              # evaluation interval during training
  AMP           : false           # use AMP in training
  DDP           : false           # use DDP training

LOSS:
  NAME          : OhemCrossEntropy          # loss function name (ohemce, ce, dice)
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.001           # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : eran_sched    # scheduler name
  POWER         : 2            # scheduler power
  WARMUP        : 0              # warmup epochs used in scheduler
  WARMUP_RATIO  : 1             # warmup ratio
  

EVAL:
  MODEL_PATH    : 'C:\final_project_eran_nadav\semantic-segmentation-main\checkpoints\model\elbit\_checkpoint_model_66.71.pth'   # trained model file path
  IMAGE_SIZE    : [540, 960]                         # evaluation image size in (h, w)
  MSF: 
    ENABLE      : false                                   # multi-scale and flip evaluation  
    FLIP        : true                                    # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation                


TEST:
  MODEL_PATH    : 'C:\final_project_eran_nadav\semantic-segmentation-main\checkpoints\model\elbit\_checkpoint_model_66.71.pth'   # trained model file path
  FILE          : 'C:\final_project_eran_nadav\semantic-segmentation-main\data\elbit_dataset\shuffeled_dataset\test'         # filename or foldername
  IMAGE_SIZE    : [540, 960]                            # inference image size in (h, w)
  OVERLAY       : true                                    # save the overlay result (image_alpha+label_alpha)